-- Comments 
CREATE TABLE STUDENT(
    SSN INT NOT NULL,
    SID INT NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    MIDDLENAME VARCHAR(20),
    LASTNAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_SSN UNIQUE(SSN),
    CONSTRAINT PK_SID PRIMARY KEY(SID)
);

CREATE TABLE DEPARTMENT (
	DEPTNAME VARCHAR(20) NOT NULL, 
	CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNAME)
);

CREATE TABLE MAJOR (
	SSN INT NOT NULL references STUDENT(SSN), 
	SID INT NOT NULL references STUDENT(SID),
	TITLE VARCHAR(20) NOT NULL, 
	DEPTNAME VARCHAR(20) NOT NULL references DEPARTMENT(DEPTNAME), 
	CONSTRAINT PK_MAJOR PRIMARY KEY (TITLE)
); 

CREATE TABLE MINOR (
 	SSN INT NOT NULL references STUDENT(SSN), 
	SID INT NOT NULL references STUDENT(SID),
	TITLE VARCHAR(20) NOT NULL, 
	DEPTNAME VARCHAR(20) NOT NULL references DEPARTMENT(DEPTNAME), 
	CONSTRAINT PK_MINOR PRIMARY KEY (TITLE)
);

CREATE TABLE PREREQ(
	CID VARCHAR(20) NOT NULL, 
	PREREQID VARCHAR(20) NOT NULL, 
	PREREQCOUNT INT NOT NULL, 
	CONSTRAINT PK_PREREQ PRIMARY KEY(PREREQID)
);

CREATE TABLE COURSES(
    CID VARCHAR(20) NOT NULL,
    PREREQID VARCHAR(20) NOT NULL references PREREQ(PREREQID),
    UNITS INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    GRADE VARCHAR(20),
    LAB_REQ BOOLEAN NOT NULL,
    CONSTRAINT PK_COURSE PRIMARY KEY(CID)
);

CREATE TABLE CLASSES (
	CID INT  NOT NULL references COURSES(CID), 
	TITLE VARCHAR(20) NOT NULL, 
	QUARTER INT NOT NULL, 
	YEAR INT NOT NULL, 
	REVIEWSESSDATE INT NOT NULL, 
	REVIEWSESSTIME INT NOT NULL,
	CONSTRAINT PK_STD4 PRIMARY KEY(TITLE)
);
 
CREATE TABLE SECTION (
	SECTID INT NOT NULL,
	TITLE VARCHAR(20) NOT NULL references CLASSES(TITLE), 
	LECTIME INT NOT NULL, 
	LECDATE INT NOT NULL, 
	DISCUSSDATE INT NOT NULL, 
	DISCUSSTIME INT NOT NULL, 
	BUILDING VARCHAR(20) NULL, 
	ROOM VARCHAR(20)  NULL,
	MAXCAP INT NULL,
	CONSTRAINT PK_STD2 PRIMARY KEY(SECTID)
); 

CREATE TABLE SECTIONSTATUS (
	SECTID INT NOT NULL references SECTION(SECTIID),
	SECTVAL INT NOT NULL, 
	WAITLISTED INT NOT NULL, 
	GRADETYPE VARCHAR(2) NOT NULL, 
	CONSTRAINT PK_ST PRIMARY KEY (SECTID,SECTVAL)
);

CREATE TABLE COURSECLASS (
	TITLE VARCHAR(20) NOT NULL references CLASSES(TITLE),
	CID VARCHAR(20) NOT NULL references COURSES(CID),
	CONSTRAINT PK_CC PRIMARY KEY (TITLE,CID) 
);

CREATE TABLE REVIEW_SES(
	SECTIONID INT NOT NULL,
	R_DATE DATE NOT NULL,
	R_TIME TIME NOT NULL	
);

CREATE TABLE PROBATION(
    SSN VARCHAR(20) NOT NULL,
    PERIOD VARCHAR(20),
    REASON BOOLEAN NOT NULL
);


CREATE TABLE REQUIRESLAB (
	CID VARCHAR(20) NOT NULL references COURSES(CID), 
	LABWORKS BOOLEAN NOT NULL, 
	CONSTRAINT PK_LAB PRIMARY KEY(LABWORKS)

);
 
﻿ 
CREATE TABLE thesis_committee(
	SID int not null references STUDENT(SID),
	TCID int not null, 
	p1 varchar(20) not null,
	p2 varchar(20) not null,
	p3 varchar(20) not null,
	p4 varchar(20), 
	CONSTRAINT PK_TCID PRIMARY KEY(TCID)
);


CREATE TABLE FACULTY(
    FNAME VARCHAR(20) NOT NULL,
    TITLE VARCHAR(20) NOT NULL,
    DEPTNAME VARCHAR(20) NOT NULL references DEPARTMENT(DEPTNAME),
    CONSTRAINT PK_FNAME PRIMARY KEY(FNAME)
);

CREATE TABLE ADVISES (
	SID int not null references STUDENT(SID), 
	FNAME VARCHAR(20) not null references FACULTY(FNAME), 
	CONSTRAINT PK_ADV PRIMARY KEY (SID, FNAME)
);

CREATE TABLE RESEARCH (
	R_ID int not null,
	SUBJECTS VARCHAR(20) not null, 
	CONSTRAINT PK_RE PRIMARY KEY(R_ID)
);

CREATE TABLE PARTICIPATE (
	SID int not null references STUDENT(SID), 
	R_ID int not null references RESEARCH(R_ID), 
	CONSTRAINT PK_PART PRIMARY KEY (SID, R_ID)
);

 
CREATE TABLE UNDERGRADUATES (
	SID int not null references STUDENT(SID), 
	COLLEGE VARCHAR(20) not null, 
	CONSTRAINT PK_C PRIMARY KEY (COLLEGE)
);

CREATE TABLE GRADUATES (
	SID int not null references STUDENT(SID), 
	TYPE VARCHAR(20) not null, 
	CONSTRAINT PK_GRAD PRIMARY KEY (SID, TYPE) 
);

CREATE TABLE REGISTER (
	SID int not null references STUDENT(SID), 
	SECTID int not null references SECTION(SECTID), 
	ATTENDANCE VARCHAR(20) not null, 
	PASTQUARTER VARCHAR(20) not null, 
	CONSTRAINT PK_REG PRIMARY KEY (SID, SECTID)
);

CREATE TABLE PREV_DEGREE (
	SID int not null references STUDENT(SID), 
	DEGREEID int not null, 
	INSTITUTION VARCHAR(20) not null, 
	DEGREETYPE VARCHAR(20) not null, 
	CONSTRAINT PK_DEG PRIMARY KEY (DEGREEID)
);


CREATE TABLE DEGREE_REQ(
	DEGREE_ID INT not null,
	DEPTNAME VARCHAR(20) references department(deptname),
	DEGREE_NAME VARCHAR(20) not null,
	DEGREE_LVL VARCHAR(20) not null,
	TOTAL_UNITS INT not null,
	DEGREE_CATAGORY VARCHAR(20) not null,
	CATAGORY_UNITS VARCHAR(20) not null,
	COURSE_NO VARCHAR(20) not null,
	GRAD_CONCENTRATION VARCHAR(20),
	CONSTRAINT PK_DEGREQ PRIMARY KEY (DEGREE_ID)
);

 


 
