-- Database: db1

-- DROP DATABASE db1;

SELECT * FROM T;

CREATE TABLE REVIEW_SES(
	SECTIONID INT NOT NULL,
	R_DATE DATE NOT NULL,
	R_TIME TIME NOT NULL	
);

CREATE TABLE COURSES(
    COURSE_NO INT NOT NULL,
    UNITS INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    GRADE VARCHAR(20),
    LAB_REQ BOOLEAN NOT NULL,
    PREREQ VARCHAR(10) NOT NULL,
    CONSTRAINT PK_COURSE PRIMARY KEY(COURSE_NO)
);

CREATE TABLE PROBATION(
    SSN VARCHAR(20) NOT NULL,
    PERIOD VARCHAR(20),
    REASON BOOLEAN NOT NULL,
);
